# Generated by Django 6.0.3 on 2026-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybus', '0003_province_district_sector_cell_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
